# Generated by Django 5.2.6 on 2025-09-25 06:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DebateSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('topic', models.TextField()),
                ('ai1_system_prompt', models.TextField(default='긍정적인 관점에서 토론하세요.')),
                ('ai2_system_prompt', models.TextField(default='부정적인 관점에서 토론하세요.')),
                ('status', models.CharField(choices=[('created', '생성됨'), ('in_progress', '진행중'), ('completed', '완료됨')], default='created', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('max_rounds', models.IntegerField(default=5)),
                ('current_round', models.IntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DebateMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('speaker', models.CharField(choices=[('user', 'User'), ('ai1', 'AI1 (긍정)'), ('ai2', 'AI2 (부정)')], max_length=10)),
                ('content', models.TextField()),
                ('round_number', models.IntegerField()),
                ('response_time', models.FloatField(blank=True, null=True)),
                ('model_used', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='debate.debatesession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DebateEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ai1_score', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)])),
                ('ai2_score', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)])),
                ('ai1_comment', models.TextField(blank=True)),
                ('ai2_comment', models.TextField(blank=True)),
                ('overall_comment', models.TextField(blank=True)),
                ('winner', models.CharField(blank=True, choices=[('ai1', 'AI1 (긍정)'), ('ai2', 'AI2 (부정)'), ('draw', '무승부')], max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evaluator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='debate.debatesession')),
            ],
        ),
    ]
